### PR TITLE
Feature 23241 migrate currency revaluation 17 aka

### PR DESCRIPTION
**Pull request by Qlasta**
migrate to v17 with fixes.

https://hive.versada.eu/work_packages/23241/activity

### CODE REVIEW

**Comment by Qlasta** [comment]
Module was not migrated by OCA, so we migrating it on forked OCA's account-closing v17 repository.

**Comment by AurelijaNorvaisaite** [comment]
@Qlasta why not contribute to OCA? as I see, there is not a lot of fixes required. And it will be hard to maintain this module if OCA will migrate it without these fixes.

**Comment by Qlasta** [comment]
> @Qlasta why not contribute to OCA? as I see, there is not a lot of fixes required. And it will be hard to maintain this module if OCA will migrate it without these fixes.

@AurelijaNorvaisaite I submitted the same changes to OCA, not sure how long it will take for them to approve. @augustinasra, is this module urgent for us, or we can wait until OCA approves it?
I suggest we can at least have it in our system for testing until they approves.

**Comment by AurelijaNorvaisaite** [comment]
@Qlasta I see that you submitted, but they won't approve it as it does not follow required guidelines. It should look like something like this:
https://github.com/OCA/account-closing/pull/248/commits
With all commits from previous versions. 
Here you can find technical method how to migrate: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

**Comment by Qlasta** [comment]
> @Qlasta I see that you submitted, but they won't approve it as it does not follow required guidelines. It should look like something like this: https://github.com/OCA/account-closing/pull/248/commits With all commits from previous versions. Here you can find technical method how to migrate: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

@AurelijaNorvaisaite thanks, understood, will change my PR.

**Comment by augustinasra** [comment]
@Qlasta it's not urgent, so we can wait for OCA approval

**Comment by Qlasta** [comment]
closing for now, PR provided to OCA. (no.302)

**Pull request closed without merging**
